# Generated by Django 2.0.5 on 2018-06-11 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('razon_social', models.CharField(max_length=140)),
                ('rfc', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=140)),
                ('codigo', models.CharField(max_length=20)),
                ('giro', models.CharField(max_length=140)),
                ('calle', models.CharField(max_length=140)),
                ('colonia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=140)),
                ('estado', models.CharField(max_length=60)),
                ('cp', models.CharField(blank=True, max_length=5)),
                ('pais', models.CharField(default='Mexico', max_length=60)),
                ('region', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('pagina_web', models.CharField(blank=True, max_length=140)),
                ('logo', models.ImageField(blank=True, upload_to='static/images/logosClientes')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
